title: DHIDB
author: Taimur Khan, Julian Oeser, and Ingolf Kühn
copyright: "2026, Helmholtz Centre for Environmental Research - UFZ"
logo: _static/DHIDB_logo.png
only_build_toc_files: true
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
repository:
  url: https://github.com/thisistaimur/dhidb
  branch: main
html:
  favicon: _static/DHIDB_logo.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
  extra_footer: >-
    DHIDB is developed at the Helmholtz Centre for Environmental Research - UFZ.
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx_copybutton
  config:
    html_css_files:
      - custom.css
    html_theme_options:
      logo:
        text: DHIDB
      show_nav_level: 2
